spring.application.name=sistema-de-atendimento
# Configuração H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8089
# JWT Properties
jwt.secret=7d8A4b2fC9e1G5hJ3kM6p9rT2v5y8zB1aC4d7fG0jL3m6qS9u2w5z8
jwt.expiration.hours=8