spring.application.name=sistema-de-atendimento
server.port=8089

# JWT Properties
jwt.secret=7d8A4b2fC9e1G5hJ3kM6p9rT2v5y8zB1aC4d7fG0jL3m6qS9u2w5z8
jwt.expiration.hours=8

# Configuração PostgreSQL (O host 'db' será o nome do container no Docker)
spring.datasource.url=jdbc:postgresql://db:5432/atendimento_db
spring.datasource.username=admin
spring.datasource.password=$up@2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true